### ISSUE TITLE
TODO-List erstellen 

### ISSUE THREAD

**Issue by PeterScholl** [HeikoDudzus/Abalone#1]
Hier fehlt dringend ein Readme für das compilieren und die Client-Server -Interaktion. ;-)

**Comment by HeikoDudzus** [comment]
Fürs erste muss die Testklasse reichen. In der steht ja alles wichtige, welche Objekte erzeugt werden müssen. Client-Server-Interaktion steht noch auf der ToDo-Liste im Wiki. Protokoll ist noch nicht festgenagelt. Vielleicht verhandeln wir das dort. Ein Issue vor einem ersten Release ist was sportlich, nicht? ;-)

**Comment by HeikoDudzus** [comment]
Sorry, ich hatte vergessen, dass die package.bluej bewusst in der gitignore steht. Dort gibt die Testklasse weitere Auskunft. Readme erstellt.
